### ISSUE TITLE
question

### ISSUE THREAD

**Issue by geraldstanje** [dispersing/HexGrid#1]
Hi,

I was wondering if it is possible to overlap the hexagonal structure on a google map image which I get via ggmap and than plot the frequency of crimes within each hexagon? cc: http://www.r-bloggers.com/visualising-thefts-using-heatmaps-in-ggplot2/

This is how to get he Chicago map and plot a heatmap:

```
## Get Chicago map chicago <- get_map(location = 'chicago', zoom = 11) 
png(filename = "Chicago.png", width = 800, height = 600, units = "px") 
ggmap(chicago) 
dev.off()

## Plotting the location heatmap 
png(filename = "Chicagomap.png", width = 800, height = 600, units = "px") 
ggmap(chicago) + geom_tile(data = locationCrimes, aes(x = long, y = lat, alpha = Frequency), fill = "red") + theme(axis.title.y = element_blank(), axis.title.x = element_blank()) 
dev.off()
```

Thanks.

**Comment by dispersing** [comment]
Hi @geraldstanje,
It is possible to overlay the grid, but not as a 2-dimensional histogram with each cell representing the frequency or proportion of points, which would just be aesthetic; i.e.:
`chicago <- get_map(location = 'chicago', zoom = 11)`
`ggmap(chicago)`
`hd <- hexgrid.coords(20, offset ="even", cell.radius = rad, rotation = "flat-topped")`
`par(new = T)`
`hexgrid.plot(hd[,,1,1], hd[,,1,2])`

Although, it wouldn't be too difficult to write the code to count the number of points within each cell.

It wasn't my intention to use this for binning and I don't use gg-stuff, but I was able to reproduce this example: [http://stackoverflow.com/questions/34525811/hexagonal-heatmap-on-map-with-stat-binhex-gives-error-geom-hex-only-works-wit](url).

I hope this helps and I am sorry that I could not be of more help!  I am just getting this off the ground and hopefully you'll see it up, running, and well documented before the year's up.

Best, 

@dispersing
